// 商品分类的列表
<template>
  <div id="category_list">
    <ul class="categorys">
      <li
        v-for="(categoryItem, itemIndex) in categoryItems"
        class="category_list_item"
        @mouseover="changeCategoryIndex(itemIndex)"
        @mouseout="removeHover"
      >
        <span
          class="iconfont"
          :style="changeStyle(itemIndex, categoryDetails[itemIndex].hoverColor)"
          >{{ categoryItem.iconDes }}</span
        >
        <a
          v-bind:href="'#' + title"
          :style="changeStyle(itemIndex, categoryDetails[itemIndex].hoverColor)"
          target="_blank"
          v-for="(title, titleIndex) in categoryItem.titles"
        >
          {{ titleIndex != 0 ? "/" : "" }}{{ title }}
        </a>
      </li>
    </ul>

    <CategoryDetail
      class="category_detail"
      :categoryDetail="selectDetail"
    ></CategoryDetail>
  </div>
</template>

<script>
import CategoryDetail from "./categoryDetail.vue";
export default {
  components: {
    CategoryDetail,
  },
  computed: {
    changeStyle() {
      return function (itemIndex, hoverColor) {
        return itemIndex == this.hoverCategoryIndex
          ? "color:" + hoverColor + "!important"
          : "red";
      };
    },
  },
  data() {
    //iconfont字符修正 在WPF中字体图标"&#xe522;"通过字段绑定需要写为"\ue522"，否在只显示字符串
    return {
      selectDetail: null,
      hoverCategoryIndex: -1,
      categoryItems: [
        { titles: ["女装", "内衣"], iconDes: "\u3459" },
        {
          titles: ["男装", "运动户外"],
          iconDes: "\u346c",
        },
        {
          titles: ["女鞋", "男鞋", "箱包"],
          iconDes: "\u346d",
        },
        {
          titles: ["美妆", "个人护理"],
          iconDes: "\u345c",
        },
        {
          titles: ["腕表", "眼镜", "珠宝饰品"],
          iconDes: "\u3452",
        },
        {
          titles: ["手机", "数码", "电脑办公"],
          iconDes: "\u3457",
        },
        { titles: ["母婴玩具"], iconDes: "\u3456" },
        {
          titles: ["零食", "茶酒", "进口食品"],
          iconDes: "\u3455",
        },
        { titles: ["生鲜水果"], iconDes: "\u3485" },
        { titles: ["大家电", "生活电器"], iconDes: "\u3454" },
        { titles: ["家具建材"], iconDes: "\u3453" },
        { titles: ["汽车", "配件", "用品"], iconDes: "\u345d" },
        { titles: ["家纺", "家饰", "鲜花"], iconDes: "\u345e" },
        { titles: ["医药保健"], iconDes: "\u3460" },
        { titles: ["厨具", "收纳", "宠物"], iconDes: "\u345f" },
        { titles: ["图书音像"], iconDes: "\u3461" },
      ],
      categoryDetails: [
        // 女装 /内衣
        {
          hoverColor: "#e54077",
          detail: [
            {
              title: "当季流行",
              items: [
                { name: "女装新品", isHot: true },
                { name: "商场同款" },
                { name: "仙女连衣裙", isHot: true },
                { name: "T恤" },
                { name: "衬衫" },
                { name: "时髦外套" },
                { name: "休闲裤" },
                { name: "牛仔裤" },
                { name: "无痕文胸", isHot: true },
                { name: "运动文胸" },
                { name: "潮流家居服", isHot: true },
                { name: "百搭船袜" },
              ],
            },
            {
              title: "精选上装",
              items: [
                { name: "毛呢外套", isHot: true },
                { name: "羽绒服", isHot: true },
                { name: "棉服", isHot: true },
                { name: "丝绒卫衣" },
                { name: "毛针织衫" },
                { name: "皮毛一体" },
                { name: "皮草" },
                { name: "毛衣" },
                { name: "衬衫" },
                { name: "卫衣" },
                { name: "针织衫" },
                { name: "T恤", isHot: true },
                { name: "短外套" },
                { name: "小西装", isHot: true },
                { name: "风衣" },
              ],
            },
            {
              title: "浪漫裙装",
              items: [
                { name: "连衣裙", isHot: true },
                { name: "半身裙" },
                { name: "A字裙", isHot: true },
                { name: "荷叶边裙", isHot: true },
                { name: "大摆裙" },
                { name: "包臀裙" },
                { name: "百褶裙", isHot: true },
                { name: "长袖" },
                { name: "连衣裙" },
                { name: "棉麻连衣裙" },
                { name: "牛仔裙" },
                { name: "蕾丝连衣裙" },
                { name: "真丝连衣裙" },
                { name: "印花连衣裙" },
              ],
            },
            {
              title: "女士下装",
              items: [
                { name: "休闲裤", isHot: true },
                { name: "阔腿裤", isHot: true },
                { name: "牛仔裤" },
                { name: "打底裤" },
                { name: "开叉运动裤", isHot: true },
                { name: "哈伦裤背带裤" },
                { name: "小脚裤西装裤" },
                { name: "短裤" },
              ],
            },
            {
              title: "特色女装",
              items: [
                { name: "时尚套装", isHot: true },
                { name: "休闲套装" },
                { name: "日系女装", isHot: true },
                { name: "精选妈妈装", isHot: true },
                { name: "大码女装" },
                { name: "职业套装" },
                { name: "优雅旗袍" },
                { name: "精致礼服" },
                { name: "婚纱" },
                { name: "唐装" },
                { name: "小码女装" },
              ],
            },
            {
              title: "文胸塑身",
              items: [
                { name: "光面文胸" },
                { name: "运动文胸" },
                { name: "美背文胸" },
                { name: "聚拢文胸" },
                { name: "大杯文胸" },
                { name: "轻薄塑身" },
              ],
            },
            {
              title: "家居服",
              items: [
                { name: "春夏家居服" },
                { name: "纯棉家居服" },
                { name: "莫代尔家居服" },
                { name: "真丝家居服" },
                { name: "春夏睡裙" },
                { name: "男士家居服" },
                { name: "情侣家居服" },
                { name: "性感睡裙" },
              ],
            },
            {
              title: "内裤背心",
              items: [
                { name: "男士内裤" },
                { name: "女式内裤" },
                { name: "男士内裤多条装" },
                { name: "女士内裤多条装" },
                { name: "莫代尔内裤" },
              ],
            },
          ],
        },
        // 男装 /运动户外
        {
          hoverColor: "#427def",
          detail: [
            {
              title: "当季流行",
              items: [
                { name: "当季新品", isHot: true },
                { name: "商场同款" },
                { name: "羽绒服", isHot: true },
                { name: "潮流卫衣", isHot: true },
                { name: "牛仔衬衫" },
                { name: "修身夹克", isHot: true },
                { name: "保暖棉服", isHot: true },
                { name: "温暖的针织衫" },
                { name: "修身西服" },
                { name: "秋冬风衣", isHot: true },
                { name: "束脚裤", isHot: true },
                { name: "破洞牛仔裤" },
                { name: "跑步鞋", isHot: true },
                { name: "休闲鞋", isHot: true },
                { name: "篮球鞋", isHot: true },
                { name: "自行车", isHot: true },
                { name: "平衡车" },
                { name: "帆布鞋" },
                { name: "运动套装" },
                { name: "运动卫衣", isHot: true },
                { name: "鱼竿", isHot: true },
                { name: "冲锋衣", isHot: true },
                { name: "跑步机", isHot: true },
                { name: "电动车", isHot: true },
              ],
            },
            {
              title: "男士外套",
              items: [
                { name: "夹克", isHot: true },
                { name: "单西" },
                { name: "棒球服" },
                { name: "棉衣", isHot: true },
                { name: "毛呢大衣", isHot: true },
                { name: "风衣" },
                { name: "西服套装", isHot: true },
                { name: "羽绒服", isHot: true },
                { name: "皮衣" },
                { name: "运动服" },
                { name: "工装外套" },
                { name: "针织开衫" },
                { name: "马甲" },
              ],
            },
            {
              title: "男士内搭",
              items: [
                { name: "短袖T恤", isHot: true },
                { name: "POLO衫", isHot: true },
                { name: "短袖衬衫" },
                { name: "背心" },
                { name: "卫衣", isHot: true },
                { name: "针织衫/毛衣" },
                { name: "长袖衬衫", isHot: true },
                { name: "长袖T恤" },
              ],
            },
            {
              title: "男士裤装",
              items: [
                { name: "小脚裤", isHot: true },
                { name: "9分裤", isHot: true },
                { name: "短裤" },
                { name: "休闲裤", isHot: true },
                { name: "牛仔裤", isHot: true },
                { name: "针织裤", isHot: true },
                { name: "西裤" },
                { name: "运动裤" },
                { name: "工装裤" },
              ],
            },
            {
              title: "特色男装",
              items: [
                { name: "潮牌", isHot: true },
                { name: "中老年" },
                { name: "加大码", isHot: true },
                { name: "职场精英" },
                { name: "中国风", isHot: true },
                { name: "情侣装" },
              ],
            },
            {
              title: "运动鞋",
              items: [
                { name: "跑步鞋", isHot: true },
                { name: "运动鞋" },
                { name: "板鞋" },
                { name: "潮鞋", isHot: true },
                { name: "休闲鞋" },
                { name: "篮球鞋", isHot: true },
                { name: "足球鞋" },
              ],
            },
            {
              title: "运动服",
              items: [
                { name: "短袖t恤", isHot: true },
                { name: "运动裤", isHot: true },
                { name: "运动内衣", isHot: true },
                { name: "速干t恤", isHot: true },
                { name: "运动Polo", isHot: true },
                { name: "运动卫衣" },
                { name: "运动套装", isHot: true },
                { name: "运动短裤", isHot: true },
                { name: "健身服", isHot: true },
                { name: "运动茄克" },
              ],
            },
            {
              title: "户外鞋服",
              items: [
                { name: "冲锋衣", isHot: true },
                { name: "抓绒衣", isHot: true },
                { name: "登山鞋", isHot: true },
                { name: "户外休闲衣" },
                { name: "军迷", isHot: true },
                { name: "钓鱼服" },
              ],
            },
          ],
        },
        // 女鞋 /男鞋 /箱包
        {
          hoverColor: "#6347ed",
          detail: [
            {
              title: "推荐女鞋",
              items: [
                { name: "潮流过膝靴", isHot: true },
                { name: "气质百搭踝靴", isHot: true },
                { name: "永远的帆布鞋" },
                { name: "流行松糕底", isHot: true },
                { name: "英伦牛津鞋" },
              ],
            },
            {
              title: "潮流男鞋",
              items: [
                { name: "商场同款", isHot: true },
                { name: "休闲鞋", isHot: true },
                { name: "正装皮鞋" },
                { name: "休闲皮鞋" },
                { name: "板鞋", isHot: true },
                { name: "户外休闲", isHot: true },
                { name: "帆布鞋" },
                { name: "运动休闲", isHot: true },
                { name: "乐福鞋" },
                { name: "豆豆鞋", isHot: true },
                { name: "布洛克", isHot: true },
                { name: "帆船鞋", isHot: true },
                { name: "布鞋" },
              ],
            },
            {
              title: "女单鞋",
              items: [
                { name: "单鞋", isHot: true },
                { name: "小白鞋" },
                { name: "商场同款", isHot: true },
                { name: "帆布鞋" },
                { name: "深口单鞋", isHot: true },
                { name: "浅口单鞋" },
                { name: "平底单鞋", isHot: true },
                { name: "高跟单鞋", isHot: true },
                { name: "坡跟单鞋", isHot: true },
                { name: "豆豆鞋" },
                { name: "乐福鞋" },
                { name: "牛津鞋" },
              ],
            },

            {
              title: "特色鞋",
              items: [
                { name: "妈妈鞋" },
                { name: "大码女鞋", isHot: true },
                { name: "小码女鞋", isHot: true },
                { name: "女内增高" },
                { name: "男内增高", isHot: true },
                { name: "软轻风" },
                { name: "爸爸鞋", isHot: true },
                { name: "大码男鞋" },
                { name: "小码男鞋", isHot: true },
              ],
            },

            {
              title: "潮流女包",
              items: [
                { name: "新品推荐", isHot: true },
                { name: "商场同款", isHot: true },
                { name: "女士钱包", isHot: true },
                { name: "单肩包" },
                { name: "斜跨包" },
                { name: "手提包" },
                { name: "手拿包" },
                { name: "腰包" },
                { name: "胸包" },
                { name: "化妆包" },
              ],
            },

            {
              title: "精品男包",
              items: [
                { name: "男士钱包", isHot: true },
                { name: "收纳包" },
                { name: "胸包" },
                { name: "腰包", isHot: true },
                { name: "手拿包" },
                { name: "手提包", isHot: true },
                { name: "斜跨包" },
                { name: "单肩包" },
                { name: "商场同款" },
                { name: "新品推荐" },
              ],
            },

            {
              title: "功能箱包",
              items: [
                { name: "旅行箱", isHot: true },
                { name: "万向轮箱" },
                { name: "旅行袋" },
                { name: "女士双肩包", isHot: true },
                { name: "男士双肩包" },
                { name: "韩版双肩包" },
                { name: "铆钉双肩包" },
                { name: "女士钱包" },
                { name: "男士钱包" },
                { name: "大容量", isHot: true },
                { name: "印花", isHot: true },
              ],
            },
          ],
        },
        // 美妆 /个人护理
        {
          hoverColor: "#e54077",
          detail: [
            {
              title: "护肤品",
              items: [
                { name: "官方直售", isHot: true },
                { name: "面膜", isHot: true },
                { name: "护肤套装", isHot: true },
                { name: "乳液面霜" },
                { name: "精华液" },
                { name: "护手霜" },
                { name: "爽肤水" },
                { name: "洁面" },
                { name: "眼霜" },
                { name: "身体乳" },
                { name: "卸妆", isHot: true },
                { name: "身体护理" },
                { name: "男士护理" },
                { name: "精油芳疗" },
                { name: "丰胸" },
                { name: "面部喷雾" },
                { name: "T区护理" },
                { name: "去角质" },
                { name: "补水", isHot: true },
                { name: "祛痘" },
                { name: "敏感修护" },
                { name: "线上专柜" },
              ],
            },
            {
              title: "彩妆",
              items: [
                { name: "时尚彩妆", isHot: true },
                { name: "香水" },
                { name: "BB霜", isHot: true },
                { name: "美容工具" },
                { name: "口红", isHot: true },
                { name: "隔离" },
                { name: "粉底" },
                { name: "粉饼" },
                { name: "气垫bb", isHot: true },
                { name: "指甲油" },
                { name: "美甲工具" },
                { name: "眉笔" },
                { name: "睫毛膏", isHot: true },
                { name: "眼线" },
                { name: "唇彩" },
                { name: "眼影" },
                { name: "蜜粉" },
                { name: "彩妆套装" },
              ],
            },

            {
              title: "男士护肤",
              items: [
                { name: "洁面" },
                { name: "爽肤水" },
                { name: "乳液/面霜" },
                { name: "面膜" },
                { name: "面部精华" },
                { name: "眼部护理" },
                { name: "防晒" },
                { name: "唇部护理" },
                { name: "T区护理" },
                { name: "控油" },
              ],
            },

            {
              title: "肤质推选",
              items: [
                { name: "混合偏油型" },
                { name: "中性偏干型", isHot: true },
                { name: "敏感性" },
                { name: "干性", isHot: true },
                { name: "油性", isHot: true },
                { name: "混合型", isHot: true },
                { name: "中性" },
              ],
            },

            {
              title: "美发护发",
              items: [
                { name: "洗发水", isHot: true },
                { name: "进口洗发水", isHot: true },
                { name: "护发素" },
                { name: "发膜" },
                { name: "洗护套装", isHot: true },
                { name: "护发精油" },
                { name: "头发造型" },
                { name: "弹力素" },
                { name: "染发霜" },
                { name: "整顶假发", isHot: true },
                { name: "假发配件" },
                { name: "男性假发" },
              ],
            },

            {
              title: "口腔护理",
              items: [
                { name: "牙膏", isHot: true },
                { name: "进口牙膏" },
                { name: "牙刷" },
                { name: "进口牙刷", isHot: true },
                { name: "漱口水", isHot: true },
                { name: "牙线" },
                { name: "牙粉" },
                { name: "口气清新剂" },
                { name: "牙贴", isHot: true },
                { name: "口腔美白" },
                { name: "假牙清洁" },
              ],
            },

            {
              title: "身体女性",
              items: [
                { name: "沐浴露", isHot: true },
                { name: "香皂" },
                { name: "泡澡浴盐" },
                { name: "护足" },
                { name: "洗手液", isHot: true },
                { name: "手动剃须刀" },
                { name: "卫生巾", isHot: true },
                { name: "成人护垫" },
                { name: "私处洗液" },
                { name: "卫生棉条" },
              ],
            },
          ],
        },
        // 腕表 /眼镜 /珠宝饰品
        {
          hoverColor: "#6347ed",
          detail: [
            {
              title: "黄金首饰",
              items: [
                { name: "耳钉", isHot: true },
                { name: "黄金项链" },
                { name: "投资黄金" },
                { name: "婚嫁套饰", isHot: true },
                { name: "黄金对戒" },
                { name: "转运珠" },
                { name: "足金饰品" },
                { name: "K金饰品" },
                { name: "商场同款" },
              ],
            },
            {
              title: "钻石彩宝",
              items: [
                { name: "结婚钻戒", isHot: true },
                { name: "钻石吊坠" },
                { name: "钻石耳饰" },
                { name: "钻石手链" },
                { name: "裸钻定制" },
                { name: "红蓝宝石", isHot: true },
                { name: "绿宝石" },
                { name: "坦桑石" },
                { name: "其他天然宝石" },
              ],
            },
            {
              title: "珍珠玉翠",
              items: [
                { name: "珍珠项链送妈妈", isHot: true },
                { name: "海水珍珠" },
                { name: "和田玉" },
                { name: "翡翠摆件" },
                { name: "翡翠手镯", isHot: true },
                { name: "翡翠项链" },
                { name: "琥珀手链" },
                { name: "天然琥珀", isHot: true },
                { name: "原矿琥珀" },
              ],
            },

            {
              title: "潮流饰品",
              items: [
                { name: "明星同款", isHot: true },
                { name: "传统银饰" },
                { name: "木手串" },
                { name: "银手镯" },
                { name: "石榴石手链" },
                { name: "开口戒指" },
                { name: "胸针", isHot: true },
                { name: "宝宝银饰" },
                { name: "手链", isHot: true },
                { name: "项链" },
                { name: "发饰", isHot: true },
                { name: "手镯" },
                { name: "耳饰" },
                { name: "戒指" },
                { name: "项坠" },
                { name: "施华洛世奇", isHot: true },
                { name: "shes", isHot: true },
                { name: "银时代" },
                { name: "伊泰莲娜" },
                { name: "PH7", isHot: true },
                { name: "Monchhichi" },
                { name: "ALEXANDRE", isHot: true },
              ],
            },
            {
              title: "腕表",
              items: [
                { name: "瑞士名表", isHot: true },
                { name: "日韩港表", isHot: true },
                { name: "欧美手表", isHot: true },
                { name: "经典国表" },
                { name: "国货精表", isHot: true },
                { name: "男表", isHot: true },
                { name: "女表", isHot: true },
                { name: "情侣表" },
                { name: "儿童手表" },
                { name: "机械表", isHot: true },
                { name: "石英表" },
                { name: "光能表" },
                { name: "防水表" },
                { name: "运动表" },
                { name: "学生表" },
                { name: "军表" },
                { name: "陶瓷表" },
              ],
            },

            {
              title: "眼镜",
              items: [
                { name: "太阳镜", isHot: true },
                { name: "墨镜" },
                { name: "眼镜框" },
                { name: "近视眼镜", isHot: true },
                { name: "防辐射眼镜" },
                { name: "老花镜", isHot: true },
                { name: "司机镜" },
                { name: "偏光镜", isHot: true },
                { name: "驾驶镜" },
                { name: "3D眼镜" },
                { name: "雷朋" },
                { name: "暴龙" },
                { name: "宝岛眼镜" },
                { name: "oakley" },
              ],
            },

            {
              title: "烟具",
              items: [
                { name: "电子烟", isHot: true },
                { name: "烟盒" },
                { name: "烟斗" },
                { name: "烟嘴" },
                { name: "烟油" },
                { name: "蒸汽烟" },
                { name: "水烟" },
                { name: "戒烟" },
                { name: "女士烟" },
                { name: "鼻烟" },
                { name: "雪茄" },
              ],
            },
            {
              title: "打火机",
              items: [
                { name: "打火机" },
                { name: "Zippo" },
                { name: "防风打火机" },
                { name: "充气打火机" },
                { name: "煤油打火机" },
                { name: "充电打火机" },
                { name: "打火机油" },
                { name: "usb打火机" },
                { name: "火柴" },
                { name: "佐罗" },
              ],
            },
          ],
        },
        // 手机 /数码 /电脑办公
        {
          hoverColor: "#427def",
          detail: [
            {
              title: "热门手机",
              items: [
                { name: "小米", isHot: true },
                { name: "iPhone" },
                { name: "魅族" },
                { name: "荣耀" },
                { name: "乐视" },
                { name: "OPPO" },
                { name: "vivo" },
                { name: "三星" },
                { name: "华为" },
              ],
            },

            {
              title: "特色手机",
              items: [
                { name: "AliOS" },
                { name: "千元指纹" },
                { name: "双卡双待" },
                { name: "大屏" },
                { name: "自拍" },
                { name: "移动" },
                { name: "联通" },
                { name: "电信" },
                { name: "合约机" },
              ],
            },

            {
              title: "手机特惠",
              items: [
                { name: "打折秒杀" },
                { name: "新品特卖" },
                { name: "实惠精选", isHot: true },
              ],
            },

            {
              title: "电脑整机",
              items: [
                { name: "笔记本", isHot: true },
                { name: "平板电脑" },
                { name: "台式机", isHot: true },
                { name: "一体机" },
                { name: "DIY" },
                { name: "游戏本" },
                { name: "iPad", isHot: true },
                { name: "Surface", isHot: true },
              ],
            },

            {
              title: "智能数码",
              items: [
                { name: "智能设备" },
                { name: "智能手表", isHot: true },
                { name: "智能手环" },
                { name: "VR眼镜" },
                { name: "智能摄像", isHot: true },
                { name: "智能健康" },
                { name: "智能机器人" },
              ],
            },

            {
              title: "游戏组装",
              items: [
                { name: "DIY电脑" },
                { name: "竞技DIY", isHot: true },
                { name: "显示器" },
                { name: "游戏本" },
                { name: "机械键盘", isHot: true },
                { name: "XBOX", isHot: true },
                { name: "游戏手柄" },
              ],
            },

            {
              title: "硬件存储",
              items: [
                { name: "显示器", isHot: true },
                { name: "机械键盘" },
                { name: "固态硬盘" },
                { name: "CPU", isHot: true },
                { name: "显卡" },
                { name: "主板" },
                { name: "高速U盘", isHot: true },
                { name: "路由器" },
              ],
            },

            {
              title: "摄影摄像",
              items: [
                { name: "相机" },
                { name: "单反", isHot: true },
                { name: "单电微单" },
                { name: "摄像机", isHot: true },
                { name: "自拍神器", isHot: true },
                { name: "拍立得" },
                { name: "镜头" },
                { name: "自拍杆", isHot: true },
              ],
            },

            {
              title: "影音娱乐",
              items: [
                { name: "耳机", isHot: true },
                { name: "天猫魔盒" },
                { name: "数码影音", isHot: true },
                { name: "家庭影院" },
                { name: "蓝牙耳机", isHot: true },
                { name: "网络播放器" },
              ],
            },

            {
              title: "办公文教",
              items: [
                { name: "文具" },
                { name: "电子书" },
                { name: "笔类／书写工具" },
                { name: "智能投影" },
                { name: "打印机" },
                { name: "保险箱" },
              ],
            },

            {
              title: "数码配件",
              items: [
                { name: "手机配件" },
                { name: "苹果配件", isHot: true },
                { name: "笔记本配件" },
                { name: "平板配件", isHot: true },
                { name: "相机配件" },
                { name: "手机车载配件" },
                { name: "kindle配件" },
                { name: "充电宝" },
                { name: "自拍杆" },
                { name: "数据线" },
                { name: "电池" },
              ],
            },
          ],
        },
        // 母婴玩具
        {
          hoverColor: "#fa5c5c",
          detail: [
            {
              title: "童装",
              items: [
                { name: "商场同款", isHot: true },
                { name: "套装" },
                { name: "裤子", isHot: true },
                { name: "外套" },
                { name: "T恤", isHot: true },
                { name: "裙子" },
                { name: "内衣裤" },
                { name: "连体衣", isHot: true },
                { name: "亲子装" },
              ],
            },

            {
              title: "婴儿服",
              items: [
                { name: "连体衣", isHot: true },
                { name: "内衣套装" },
                { name: "裤子" },
                { name: "婴儿礼盒", isHot: true },
                { name: "外套" },
                { name: "家居服" },
                { name: "T恤" },
                { name: "反穿衣" },
                { name: "肚兜", isHot: true },
              ],
            },

            {
              title: "童鞋",
              items: [
                { name: "学步鞋", isHot: true },
                { name: "运动鞋", isHot: true },
                { name: "亲子鞋", isHot: true },
                { name: "帆布鞋", isHot: true },
                { name: "皮鞋", isHot: true },
                { name: "雨靴" },
                { name: "靴子" },
                { name: "拖鞋" },
                { name: "棉鞋" },
                { name: "凉鞋" },
              ],
            },

            {
              title: "车床用品",
              items: [
                { name: "婴儿推车", isHot: true },
                { name: "学步车" },
                { name: "安全座椅", isHot: true },
                { name: "婴儿背带" },
                { name: "腰凳" },
                { name: "婴儿床", isHot: true },
                { name: "餐椅" },
                { name: "睡袋" },
                { name: "抱被" },
              ],
            },

            {
              title: "喂养",
              items: [
                { name: "奶瓶", isHot: true },
                { name: "奶嘴" },
                { name: "水杯", isHot: true },
                { name: "餐具" },
                { name: "消毒锅" },
                { name: "辅食机", isHot: true },
                { name: "调奶器" },
                { name: "暖奶器" },
                { name: "围嘴" },
              ],
            },

            {
              title: "洗护",
              items: [
                { name: "洗发水" },
                { name: "沐浴露", isHot: true },
                { name: "润肤" },
                { name: "浴盆" },
                { name: "湿巾", isHot: true },
                { name: "洗衣液" },
                { name: "洗衣皂", isHot: true },
                { name: "理发器" },
                { name: "驱虫止痒" },
              ],
            },

            {
              title: "玩具",
              items: [
                { name: "婴儿玩具", isHot: true },
                { name: "儿童自行车", isHot: true },
                { name: "儿童电动车" },
                { name: "毛绒玩具" },
                { name: "积木", isHot: true },
                { name: "电动遥控" },
                { name: "儿童箱包" },
              ],
            },

            {
              title: "天猫动漫",
              items: [
                { name: "动漫周边", isHot: true },
                { name: "影视周边" },
                { name: "手办", isHot: true },
                { name: "高达", isHot: true },
                { name: "魔术道具" },
                { name: "COSPLAY" },
                { name: "桌游" },
                { name: "变形金刚" },
              ],
            },

            {
              title: "奶粉",
              items: [
                { name: "牛奶粉", isHot: true },
                { name: "羊奶粉" },
                { name: "特殊配方奶粉" },
                { name: "宝宝辅食", isHot: true },
                { name: "宝宝零食" },
                { name: "宝宝营养", isHot: true },
                { name: "DHA" },
              ],
            },

            {
              title: "纸尿裤",
              items: [
                { name: "纸尿裤" },
                { name: "拉拉裤", isHot: true },
                { name: "纸尿片" },
                { name: "L", isHot: true },
                { name: "XL" },
                { name: "M" },
                { name: "S" },
                { name: "NB" },
                { name: "新生儿组合", isHot: true },
              ],
            },

            {
              title: "孕产",
              items: [
                { name: "孕产用品", isHot: true },
                { name: "孕妈洗护", isHot: true },
                { name: "孕妈装", isHot: true },
                { name: "月子服" },
                { name: "哺乳文胸" },
                { name: "防辐射" },
                { name: "吸奶器" },
                { name: "待产包" },
              ],
            },
          ],
        },
        // 零食 /茶酒 /进口食品
        {
          hoverColor: "#f7a831",
          detail: [
            {
              title: "进口食品",
              items: [
                { name: "进口零食", isHot: true },
                { name: "进口巧克力", isHot: true },
                { name: "进口饼干", isHot: true },
                { name: "进口糖果" },
                { name: "进口坚果", isHot: true },
                { name: "进口果干" },
                { name: "进口橄榄油" },
                { name: "进口牛奶", isHot: true },
                { name: "进口咖啡", isHot: true },
                { name: "进口饮料" },
                { name: "进口葡萄酒" },
                { name: "进口洋酒", isHot: true },
                { name: "进口啤酒", isHot: true },
              ],
            },
            {
              title: "休闲零食",
              items: [
                { name: "零食", isHot: true },
                { name: "坚果", isHot: true },
                { name: "饼干", isHot: true },
                { name: "蛋糕" },
                { name: "红枣" },
                { name: "巧克力" },
                { name: "猪肉脯" },
                { name: "膨化食品" },
                { name: "蜜饯" },
                { name: "鸭脖" },
                { name: "糖果" },
                { name: "豆干" },
                { name: "曲奇" },
                { name: "海苔" },
                { name: "肉松饼" },
                { name: "牛肉干" },
                { name: "鱿鱼丝" },
                { name: "糕点" },
              ],
            },
            {
              title: "酒类",
              items: [
                { name: "白酒", isHot: true },
                { name: "红酒", isHot: true },
                { name: "洋酒" },
                { name: "啤酒" },
                { name: "黄酒" },
                { name: "保健酒" },
                { name: "预调酒" },
                { name: "配制酒" },
                { name: "葡萄酒", isHot: true },
              ],
            },
            {
              title: "茶叶",
              items: [
                { name: "西湖龙井", isHot: true },
                { name: "安吉白茶" },
                { name: "绿茶", isHot: true },
                { name: "大红袍" },
                { name: "铁观音" },
                { name: "普洱茶" },
                { name: "玫瑰花茶" },
                { name: "柠檬片" },
                { name: "菊花茶" },
                { name: "花茶" },
                { name: "天然粉粉" },
                { name: "金骏眉" },
                { name: "红茶" },
              ],
            },
            {
              title: "乳品冲饮",
              items: [
                { name: "牛奶", isHot: true },
                { name: "酸奶", isHot: true },
                { name: "成人奶粉" },
                { name: "儿童奶" },
                { name: "速溶咖啡" },
                { name: "滤挂咖啡", isHot: true },
                { name: "咖啡豆" },
                { name: "麦片" },
                { name: "奶茶" },
                { name: "柚子茶" },
                { name: "果汁" },
                { name: "汽水" },
                { name: "功能饮料" },
                { name: "饮用水" },
              ],
            },
            {
              title: "粮油速食",
              items: [
                { name: "橄榄油", isHot: true },
                { name: "食用油" },
                { name: "大米", isHot: true },
                { name: "薏米" },
                { name: "玉米" },
                { name: "面粉" },
                { name: "银耳" },
                { name: "桂圆干" },
                { name: "香肠" },
                { name: "木耳" },
                { name: "香菇" },
                { name: "方便面", isHot: true },
                { name: "手抓饼" },
                { name: "黄油", isHot: true },
                { name: "意大利面" },
                { name: "蛋挞皮" },
                { name: "调味品" },
                { name: "红糖" },
                { name: "进口泡面" },
                { name: "粽子" },
                { name: "寿司" },
              ],
            },
            {
              title: "生鲜水果",
              items: [
                { name: "牛排", isHot: true },
                { name: "芒果" },
                { name: "奇异果", isHot: true },
                { name: "蟹" },
                { name: "三文鱼", isHot: true },
                { name: "虾" },
                { name: "车厘子", isHot: true },
                { name: "进口鳕鱼" },
                { name: "海参", isHot: true },
                { name: "苹果" },
                { name: "榴莲", isHot: true },
                { name: "牛肉" },
                { name: "牛油果", isHot: true },
                { name: "土鸡" },
                { name: "冰淇淋", isHot: true },
                { name: "鸡蛋" },
              ],
            },
          ],
        },
        // 生鲜水果
        {
          hoverColor: "#f7a831",
          hotBrands: [
            "https://img.alicdn.com/imgextra/i2/793475151/TB2PMxWa7yWBuNjy0FpXXassXXa_!!793475151.jpg_170x120q30.jpg",
            "https://img.alicdn.com/imgextra/i3/1734796729/TB2AaE0emMmBKNjSZTEXXasKpXa_!!1734796729.jpg_170x120q30.jpg",
            "https://img.alicdn.com/imgextra/i2/2217550171/TB2p.jjmY_I8KJjy1XaXXbsxpXa_!!2217550171.jpg_170x120q30.jpg",
            "https://img.alicdn.com/imgextra/i4/762551010/TB2J0lUepkoBKNjSZFkXXb4tFXa_!!762551010.png_170x120q30.jpg",
            "https://img.alicdn.com/imgextra/i2/2255664523/TB2in5hgiCYBuNkSnaVXXcMsVXa_!!2255664523.jpg_170x120q30.jpg",
            "https://img.alicdn.com/imgextra/i1/894224787/TB2oS7gov1TBuNjy0FjXXajyXXa_!!894224787.jpg_170x120q30.jpg",
            "https://img.alicdn.com/imgextra/i3/2095494343/TB2Qv_jlFXXXXaHXpXXXXXXXXXX_!!2095494343.jpg_170x120q30.jpg",
            "https://img.alicdn.com/imgextra/i4/1733566698/TB2WrL9or1YBuNjSszhXXcUsFXa_!!1733566698.jpg_170x120q30.jpg",
            "https://img.alicdn.com/imgextra/i1/1579528508/TB2E9rRov9TBuNjy1zbXXXpepXa_!!1579528508.png_170x120q30.jpg",
            "//img.alicdn.com/bao/uploaded/TB14lgnlnnI8KJjSszgwu38ApXa.png_170x120q30.jpg",
          ],
          detail: [
            {
              title: "新鲜蔬菜",
              items: [
                { name: "土豆" },
                { name: "番薯", isHot: true },
                { name: "山药", isHot: true },
                { name: "莲藕" },
                { name: "净菜" },
                { name: "玉米" },
                { name: "秋葵" },
                { name: "大蒜", isHot: true },
                { name: "生姜" },
                { name: "南瓜" },
              ],
            },
            {
              title: "冰淇淋",
              items: [
                { name: "冰淇淋" },
                { name: "哈根达斯", isHot: true },
                { name: "movenpick莫凡彼" },
                { name: "本杰瑞" },
                { name: "tip-top冰淇淋", isHot: true },
              ],
            },
            {
              title: "蛋类",
              items: [
                { name: "鸡蛋", isHot: true },
                { name: "鸭蛋" },
                { name: "鹅蛋" },
                { name: "鸽子蛋" },
                { name: "鹌鹑蛋" },
                { name: "松花皮蛋" },
                { name: "咸鸭蛋", isHot: true },
                { name: "喜蛋" },
              ],
            },

            {
              title: "肉类",
              items: [
                { name: "牛排", isHot: true },
                { name: "牛腩", isHot: true },
                { name: "牛腱子" },
                { name: "牛肉" },
                { name: "牛尾" },
                { name: "牛肉串" },
                { name: "牛杂" },
                { name: "羊腿" },
                { name: "羊排", isHot: true },
                { name: "羊肉串" },
                { name: "羊蝎子" },
                { name: "鸡肉" },
                { name: "鸡翅", isHot: true },
                { name: "鸡胸" },
                { name: "鸡腿" },
                { name: "鸭肉" },
                { name: "乳鸽" },
                { name: "鹅肉" },
              ],
            },

            {
              title: "海鲜水产",
              items: [
                { name: "鳕鱼" },
                { name: "三文鱼", isHot: true },
                { name: "金枪鱼" },
                { name: "鲽鱼" },
                { name: "斑鱼" },
                { name: "比目鱼" },
                { name: "多春鱼", isHot: true },
                { name: "马鲛鱼" },
                { name: "龙利鱼", isHot: true },
                { name: "秋刀鱼" },
                { name: "带鱼" },
                { name: "海带" },
                { name: "墨鱼" },
                { name: "海参", isHot: true },
                { name: "海蜇" },
                { name: "鱿鱼" },
                { name: "甲鱼" },
                { name: "大闸蟹", isHot: true },
                { name: "帝王蟹", isHot: true },
                { name: "雪蟹" },
                { name: "黄金蟹" },
                { name: "鱼丸" },
                { name: "鱼糕/鱼饼" },
                { name: "干贝/瑶柱" },
                { name: "虾仁" },
                { name: "活虾" },
                { name: "冻虾", isHot: true },
                { name: "生蚝" },
                { name: "北极贝" },
                { name: "扇贝", isHot: true },
                { name: "贝类" },
              ],
            },

            {
              title: "新鲜水果",
              items: [
                { name: "奇异果", isHot: true },
                { name: "车厘子/樱桃" },
                { name: "芒果", isHot: true },
                { name: "牛油果" },
                { name: "火龙果", isHot: true },
                { name: "苹果" },
                { name: "橙子" },
                { name: "凤梨", isHot: true },
                { name: "榴莲", isHot: true },
                { name: "山竹" },
                { name: "木瓜" },
                { name: "柠檬" },
                { name: "百香果", isHot: true },
                { name: "椰青" },
                { name: "番荔枝/释迦" },
                { name: "龙眼" },
                { name: "蓝莓" },
                { name: "梨" },
                { name: "提子" },
                { name: "柚子" },
                { name: "芭乐" },
                { name: "莲雾" },
                { name: "桃" },
                { name: "草莓" },
                { name: "西柚" },
                { name: "荔枝" },
                { name: "石榴" },
                { name: "葡萄/提子", isHot: true },
                { name: "哈密瓜", isHot: true },
                { name: "枇杷" },
                { name: "李子" },
                { name: "西瓜" },
                { name: "菠萝" },
                { name: "桔子", isHot: true },
                { name: "香蕉" },
                { name: "杨桃" },
                { name: "红毛丹/毛荔枝" },
              ],
            },

            {
              title: "精选干货",
              items: [
                { name: "干贝/瑶柱" },
                { name: "虾皮/虾米/海米", isHot: true },
                { name: "大虾干" },
                { name: "花胶/鱼胶", isHot: true },
                { name: "海带" },
                { name: "紫菜", isHot: true },
                { name: "鱼干" },
                { name: "墨鱼干" },
              ],
            },
            {
              title: "即食海鲜",
              items: [
                { name: "鱼类罐头" },
                { name: "贝类罐头" },
                { name: "香辣小龙虾" },
                { name: "即食蟹类" },
                { name: "北极甜虾" },
                { name: "即食虾类" },
                { name: "金枪鱼罐头" },
                { name: "三文鱼罐头" },
                { name: "丁香鱼罐头" },
              ],
            },
          ],
        },
        // 大家电 /生活电器
        {
          hoverColor: "#427def",
          detail: [
            {
              title: "平板电视",
              items: [
                { name: "4K超高清", isHot: true },
                { name: "国产" },
                { name: "外资品牌" },
                { name: "曲面", isHot: true },
                { name: "智能电视" },
                { name: "超级大屏", isHot: true },
                { name: "云电视" },
                { name: "客厅首选", isHot: true },
              ],
            },
            {
              title: "空调",
              items: [
                { name: "热门之选" },
                { name: "节能", isHot: true },
                { name: "智能", isHot: true },
                { name: "变频" },
                { name: "艺术柜机" },
                { name: "挂机", isHot: true },
                { name: "1.5匹" },
                { name: "中央空调" },
              ],
            },

            {
              title: "冰箱",
              items: [
                { name: "热门之选" },
                { name: "无霜", isHot: true },
                { name: "三门" },
                { name: "对开门", isHot: true },
                { name: "电脑温控" },
                { name: "智能", isHot: true },
                { name: "冷柜" },
                { name: "酒柜" },
              ],
            },

            {
              title: "洗衣机",
              items: [
                { name: "滚筒洗", isHot: true },
                { name: "波轮洗" },
                { name: "洗烘一体", isHot: true },
                { name: "迷你" },
                { name: "烘干机" },
                { name: "双缸/双桶" },
                { name: "热门", isHot: true },
                { name: "大容量" },
              ],
            },

            {
              title: "厨房大电",
              items: [
                { name: "烟灶套装", isHot: true },
                { name: "嵌入式烤箱" },
                { name: "嵌入式蒸箱", isHot: true },
                { name: "燃气灶" },
                { name: "消毒柜" },
                { name: "洗碗机", isHot: true },
                { name: "集成灶" },
              ],
            },

            {
              title: "热水器",
              items: [
                { name: "电热水器" },
                { name: "燃气热水器" },
                { name: "遥控", isHot: true },
                { name: "恒温", isHot: true },
                { name: "小厨宝" },
                { name: "太阳能" },
                { name: "即热式" },
                { name: "空气能" },
              ],
            },

            {
              title: "中式厨房",
              items: [
                { name: "净水器", isHot: true },
                { name: "电饭煲" },
                { name: "豆浆机", isHot: true },
                { name: "电热水壶" },
                { name: "电压力锅" },
                { name: "电磁炉", isHot: true },
                { name: "养生壶" },
              ],
            },

            {
              title: "西式厨房",
              items: [
                { name: "烤箱", isHot: true },
                { name: "料理机" },
                { name: "微波炉" },
                { name: "榨汁机" },
                { name: "原汁机", isHot: true },
                { name: "面包机" },
                { name: "咖啡机", isHot: true },
                { name: "电炸锅" },
              ],
            },

            {
              title: "生活电器",
              items: [
                { name: "扫地机器人", isHot: true },
                { name: "空气净化器", isHot: true },
                { name: "吸尘器" },
                { name: "除湿机" },
                { name: "取暖器", isHot: true },
                { name: "挂烫机" },
                { name: "干衣机" },
              ],
            },

            {
              title: "个护健康",
              items: [
                { name: "剃须刀", isHot: true },
                { name: "吹风机" },
                { name: "电动牙刷", isHot: true },
                { name: "体重秤", isHot: true },
                { name: "理发器" },
                { name: "足浴器" },
                { name: "按摩椅", isHot: true },
              ],
            },

            {
              title: "精品推荐",
              items: [
                { name: "脱毛器", isHot: true },
                { name: "吊扇" },
                { name: "冰淇淋机", isHot: true },
                { name: "碎冰机", isHot: true },
                { name: "空调扇" },
                { name: "瘦身带" },
                { name: "冷饮机", isHot: true },
                { name: "炒冰机" },
                { name: "电子灭蚊器" },
                { name: "冰淇淋机" },
                { name: "除湿机" },
                { name: "干衣机" },
              ],
            },
          ],
        },
        // 家具建材
        {
          hoverColor: "#dd2727",
          detail: [
            {
              title: "成套家具",
              items: [
                { name: "客厅成套家具", isHot: true },
                { name: "餐厅成套家具" },
                { name: "卧室成套家具", isHot: true },
                { name: "儿童成套家具" },
              ],
            },
            {
              title: "客厅餐厅",
              items: [
                { name: "沙发", isHot: true },
                { name: "布艺沙发" },
                { name: "皮艺沙发", isHot: true },
                { name: "实木沙发" },
                { name: "懒人沙发" },
                { name: "电视柜", isHot: true },
                { name: "茶几" },
                { name: "鞋柜", isHot: true },
                { name: "单人沙发" },
                { name: "餐桌", isHot: true },
                { name: "餐椅" },
                { name: "酒柜" },
                { name: "餐边柜", isHot: true },
                { name: "吧台" },
                { name: "玄关柜", isHot: true },
                { name: "边几" },
              ],
            },
            {
              title: "卧室家具",
              items: [
                { name: "床", isHot: true },
                { name: "衣柜" },
                { name: "床垫" },
                { name: "简易衣柜" },
                { name: "乳胶床垫", isHot: true },
                { name: "弹簧床垫" },
                { name: "棕床垫" },
                { name: "实木床", isHot: true },
                { name: "双人床", isHot: true },
              ],
            },
            {
              title: "书房儿童",
              items: [
                { name: "电脑桌", isHot: true },
                { name: "电脑椅" },
                { name: "书桌" },
                { name: "办公桌", isHot: true },
                { name: "书架" },
                { name: "书柜", isHot: true },
                { name: "连体书桌柜" },
                { name: "折叠床/椅", isHot: true },
                { name: "花架" },
                { name: "儿童床", isHot: true },
                { name: "高低床", isHot: true },
                { name: "儿童床垫" },
                { name: "儿童沙发" },
                { name: "儿童椅" },
                { name: "儿童学习桌", isHot: true },
                { name: "儿童衣柜" },
              ],
            },
            {
              title: "家装主材",
              items: [
                { name: "强化复合地板", isHot: true },
                { name: "瓷砖", isHot: true },
                { name: "墙纸" },
                { name: "涂料", isHot: true },
                { name: "瓷砖背景墙" },
                { name: "油漆" },
                { name: "地板" },
                { name: "硅藻泥" },
              ],
            },
            {
              title: "厨房卫浴",
              items: [
                { name: "浴霸" },
                { name: "集成吊顶" },
                { name: "马桶", isHot: true },
                { name: "淋浴花洒套装" },
                { name: "浴室柜组合" },
                { name: "水槽套餐" },
                { name: "智能马桶盖", isHot: true },
              ],
            },
            {
              title: "灯饰照明",
              items: [
                { name: "吸顶灯", isHot: true },
                { name: "吊灯" },
                { name: "水晶吊灯" },
                { name: "筒灯" },
                { name: "射灯", isHot: true },
                { name: "灯带", isHot: true },
                { name: "灯泡" },
                { name: "壁灯" },
                { name: "灯具套餐", isHot: true },
                { name: "铜灯" },
              ],
            },
            {
              title: "五金工具",
              items: [
                { name: "接线板" },
                { name: "开关插座", isHot: true },
                { name: "USB插座" },
                { name: "指纹锁", isHot: true },
                { name: "工具箱", isHot: true },
                { name: "监控摄像头", isHot: true },
                { name: "门锁" },
                { name: "拉手" },
              ],
            },
            {
              title: "全屋定制",
              items: [
                { name: "全屋定制", isHot: true },
                { name: "定制橱柜" },
                { name: "定制衣柜", isHot: true },
                { name: "门", isHot: true },
                { name: "木门" },
                { name: "榻榻米" },
                { name: "门窗" },
                { name: "特权订金", isHot: true },
              ],
            },
            {
              title: "装修设计",
              items: [
                { name: "装修特权", isHot: true },
                { name: "全包", isHot: true },
                { name: "半包", isHot: true },
                { name: "拎包入住", isHot: true },
                { name: "局部装修", isHot: true },
                { name: "设计" },
                { name: "软装配饰" },
                { name: "监理" },
              ],
            },
          ],
        },
        // 汽车 /配件 /用品
        {
          hoverColor: "#427def",
          hotBrands: [
            "https://img.alicdn.com/bao/uploaded/i2/0/T1FKaeXz4gXXXRih2H_!!0.jpg_170x120q30.jpg",
            "https://img.alicdn.com/bao/uploaded/TB1n0lsHFXXXXX1XVXXSutbFXXX.jpg_170x120q30.jpg",
            "https://img.alicdn.com/bao/uploaded/TB1uDGlIFXXXXbUaXXXSutbFXXX.jpg_170x120q30.jpg",
            "https://img.alicdn.com/bao/uploaded/http://gtms01.alicdn.com/tps/i1/TB1b.F3FVXXXXazXFXXXD.cNVXX-400-200.png_170x120q30.jpg",
            "https://img.alicdn.com/bao/uploaded/TB11k2qLFXXXXa.XpXXSutbFXXX.jpg_170x120q30.jpg",
            "https://img.alicdn.com/bao/uploaded/TB1Itb6JVXXXXXAXVXXSutbFXXX.jpg_170x120q30.jpg",
            "https://img.alicdn.com/bao/uploaded/TB1e5WbLXXXXXXmXXXXSutbFXXX.jpg_170x120q30.jpg",
            "https://img.alicdn.com/bao/uploaded/TB1jj3JLFXXXXXcXpXXSutbFXXX.jpg_170x120q30.jpg",
            "https://img.alicdn.com/bao/uploaded/http://gtms04.alicdn.com/tps/i4/TB1xaJ5FVXXXXXnXpXXXD.cNVXX-400-200.png_170x120q30.jpg",
            "https://img.alicdn.com/bao/uploaded/TB1US6WLpXXXXarXpXXSutbFXXX.jpg_170x120q30.jpg",
            "https://img.alicdn.com/bao/uploaded/TB1tvPzJFXXXXbRXVXXSutbFXXX.jpg_170x120q30.jpg",
            "https://img.alicdn.com/bao/uploaded/TB1zWUQLFXXXXaQXpXXwu0bFXXX.png_170x120q30.jpg",
            "https://img.alicdn.com/bao/uploaded/TB1DKEPIVXXXXXXXFXXSutbFXXX.jpg_170x120q30.jpg",
            "https://img.alicdn.com/bao/uploaded/TB1EtVFLXXXXXaLXXXXSutbFXXX.jpg_170x120q30.jpg",
            "https://img.alicdn.com/tfs/TB1vY6furvpK1RjSZPiXXbmwXXa-400-200.jpg_170x120q30.jpg",
            "https://img.alicdn.com/tfs/TB1utazv7voK1RjSZFwXXciCFXa-170-85.png_170x120q30.jpg",
          ],
          detail: [
            {
              title: "整车",
              items: [
                { name: "v60一口价39.99万" },
                { name: "超级试驾", isHot: true },
                { name: "订金购车" },
                { name: "新能源汽车" },
                { name: "轿车" },
                { name: "SUV" },
                { name: "MPV" },
              ],
            },

            {
              title: "座垫脚垫",
              items: [
                { name: "秋冬座垫", isHot: true },
                { name: "汽车脚垫" },
                { name: "专用座垫" },
                { name: "专用座套" },
                { name: "女性座垫", isHot: true },
                { name: "通用座垫" },
              ],
            },

            {
              title: "机油轮胎",
              items: [
                { name: "全合成机油", isHot: true },
                { name: "半合成机油" },
                { name: "矿物质机油" },
                { name: "汽车轮胎" },
                { name: "雪地胎", isHot: true },
                { name: "防爆胎" },
              ],
            },

            {
              title: "电子导航",
              items: [
                { name: "行车记录仪", isHot: true },
                { name: "安全预警仪" },
                { name: "后视镜导航", isHot: true },
                { name: "车载导航", isHot: true },
                { name: "便携式导航" },
                { name: "GPS定位" },
              ],
            },

            {
              title: "车载电器",
              items: [
                { name: "空气净化器", isHot: true },
                { name: "吸尘器" },
                { name: "车载冷暖箱", isHot: true },
                { name: "车载MP3" },
                { name: "逆变器" },
                { name: "手机充电器", isHot: true },
                { name: "一拖三" },
              ],
            },

            {
              title: "维修保养",
              items: [
                { name: "雨刮器" },
                { name: "空调滤芯", isHot: true },
                { name: "机油滤芯", isHot: true },
                { name: "刹车片", isHot: true },
                { name: "火花塞" },
                { name: "汽车电瓶", isHot: true },
                { name: "大灯总成" },
              ],
            },

            {
              title: "美容清洗",
              items: [
                { name: "洗车机" },
                { name: "水枪" },
                { name: "车蜡" },
                { name: "底盘装甲" },
                { name: "镀晶" },
                { name: "汽油添加剂" },
                { name: "玻璃水" },
                { name: "补漆笔" },
              ],
            },

            {
              title: "安全自驾",
              items: [
                { name: "安全座椅", isHot: true },
                { name: "车载提篮" },
                { name: "轮胎报警器", isHot: true },
                { name: "充气泵" },
                { name: "安全锤" },
                { name: "应急工具" },
                { name: "应急电源" },
              ],
            },

            {
              title: "外饰改装",
              items: [
                { name: "汽车贴膜", isHot: true },
                { name: "装饰灯" },
                { name: "改色膜" },
                { name: "脚踏板" },
                { name: "车顶架" },
                { name: "汽车车衣" },
                { name: "车顶箱" },
                { name: "装饰条" },
              ],
            },

            {
              title: "汽车服务",
              items: [
                { name: "天猫养车", isHot: true },
                { name: "加油卡" },
                { name: "4S保养", isHot: true },
                { name: "上门保养" },
                { name: "连锁保养" },
                { name: "镀晶服务" },
                { name: "打蜡服务" },
              ],
            },
          ],
        },
        // 家纺 /家饰 /鲜花
        {
          hoverColor: "#f7a831",
          detail: [
            {
              title: "当季热卖",
              items: [
                { name: "印花四件套" },
                { name: "羽绒被", isHot: true },
                { name: "蚕丝被" },
                { name: "羊毛被" },
                { name: "棉花被" },
                { name: "毛毯" },
                { name: "床笠" },
                { name: "冬季棉拖", isHot: true },
                { name: "沙发垫" },
                { name: "地毯" },
                { name: "浴巾" },
                { name: "定制窗帘" },
                { name: "抱枕被子两用" },
                { name: "坐垫" },
                { name: "国际家纺床品", isHot: true },
                { name: "国际居家布艺" },
                { name: "国际家居饰品" },
              ],
            },
            {
              title: "床上用品",
              items: [
                { name: "四件套", isHot: true },
                { name: "枕头" },
                { name: "枕芯" },
                { name: "床单" },
                { name: "被子" },
                { name: "被套" },
                { name: "床垫" },
                { name: "针织棉四件套", isHot: true },
                { name: "床帘" },
                { name: "枕套" },
                { name: "真丝枕套" },
                { name: "枕巾" },
                { name: "毯子", isHot: true },
                { name: "毛巾毯" },
                { name: "乳胶枕", isHot: true },
                { name: "颈椎枕" },
                { name: "U型枕" },
                { name: "记忆枕" },
                { name: "婚庆床品", isHot: true },
                { name: "儿童床品", isHot: true },
                { name: "床罩" },
              ],
            },
            {
              title: "居家布艺",
              items: [
                { name: "窗帘" },
                { name: "遮光窗帘", isHot: true },
                { name: "成品窗帘" },
                { name: "进口地毯" },
                { name: "客厅地毯", isHot: true },
                { name: "卧室地毯" },
                { name: "沙发套", isHot: true },
                { name: "沙发巾" },
                { name: "家居拖鞋" },
                { name: "女士棉拖", isHot: true },
                { name: "情侣拖鞋" },
                { name: "毛巾" },
                { name: "纯棉毛巾" },
                { name: "浴袍" },
                { name: "地垫" },
                { name: "防滑地垫", isHot: true },
                { name: "儿童泡沫地垫" },
                { name: "抱枕", isHot: true },
                { name: "靠垫" },
                { name: "坐垫", isHot: true },
                { name: "桌布" },
                { name: "防水桌布" },
                { name: "餐垫" },
                { name: "窗帘杆" },
                { name: "十字绣", isHot: true },
                { name: "十字绣抱枕" },
                { name: "门帘" },
                { name: "飘窗垫", isHot: true },
                { name: "钻石画" },
                { name: "防尘罩" },
                { name: "百叶帘", isHot: true },
              ],
            },
            {
              title: "家居饰品",
              items: [
                { name: "墙贴", isHot: true },
                { name: "墙纸自粘" },
                { name: "壁纸", isHot: true },
                { name: "3d立体墙贴" },
                { name: "花瓶" },
                { name: "摆件", isHot: true },
                { name: "相框" },
                { name: "装饰画", isHot: true },
                { name: "电视背景墙" },
                { name: "仿真花", isHot: true },
                { name: "闹钟" },
                { name: "玻璃贴纸" },
                { name: "结婚礼物" },
                { name: "香薰炉" },
                { name: "电表箱装饰画" },
                { name: "招财猫" },
                { name: "雕刻工艺" },
                { name: "果盘" },
                { name: "数字油画", isHot: true },
                { name: "玻璃花瓶" },
                { name: "冰箱贴" },
                { name: "首饰盒" },
                { name: "壁饰", isHot: true },
              ],
            },
            {
              title: "鲜花绿植",
              items: [
                { name: "红玫瑰", isHot: true },
                { name: "香槟玫瑰", isHot: true },
                { name: "百合" },
                { name: "永生花", isHot: true },
                { name: "萌多肉", isHot: true },
                { name: "绿植盆栽" },
                { name: "表白送花", isHot: true },
                { name: "康乃馨" },
                { name: "花束混搭" },
                { name: "进口玫瑰", isHot: true },
                { name: "多肉植物" },
                { name: "微景观", isHot: true },
                { name: "仿真花绢花" },
                { name: "情人节送花" },
                { name: "生日送花" },
                { name: "鲜花礼盒" },
                { name: "多肉花盆" },
                { name: "室内植物" },
                { name: "园艺工具", isHot: true },
                { name: "绿萝盆栽" },
                { name: "干花装饰", isHot: true },
              ],
            },
          ],
        },
        // 医药保健
        {
          hoverColor: "#3bc7b0",
          detail: [
            {
              title: "保健品",
              items: [
                { name: "营养补充剂", isHot: true },
                { name: "芦荟" },
                { name: "玛卡" },
                { name: "减肥" },
                { name: "胶原蛋白" },
                { name: "维生素C", isHot: true },
                { name: "鱼油" },
                { name: "美容养颜" },
                { name: "保健食品" },
                { name: "缓解体力疲劳", isHot: true },
                { name: "辅助降血脂", isHot: true },
                { name: "增加骨密度" },
                { name: "护肝" },
                { name: "减肥" },
                { name: "通便", isHot: true },
                { name: "抗氧化" },
                { name: "改善睡眠" },
                { name: "祛黄褐斑" },
                { name: "减肥茶" },
                { name: "酵素" },
                { name: "左旋肉碱" },
                { name: "增肌粉", isHot: true },
                { name: "安神补脑" },
              ],
            },
            {
              title: "滋补品",
              items: [
                { name: "滋补养生", isHot: true },
                { name: "蜂蜜" },
                { name: "石斛" },
                { name: "阿胶" },
                { name: "黑枸杞" },
                { name: "冬虫夏草" },
                { name: "青钱柳" },
                { name: "西洋参", isHot: true },
                { name: "人参", isHot: true },
                { name: "藏红花" },
                { name: "蜂胶" },
                { name: "阿胶糕" },
                { name: "灵芝孢子粉" },
                { name: "黄芪" },
                { name: "阿胶块", isHot: true },
                { name: "燕窝" },
                { name: "铁皮枫斗" },
                { name: "三七粉" },
                { name: "蜂王浆", isHot: true },
                { name: "雪蛤" },
                { name: "四物汤" },
                { name: "山药" },
                { name: "牛蒡茶" },
                { name: "虫草" },
                { name: "当归" },
                { name: "鹿茸" },
                { name: "固元膏", isHot: true },
              ],
            },
            {
              title: "医药",
              items: [
                { name: "感冒咳嗽" },
                { name: "腰腿疼痛", isHot: true },
                { name: "妇科用药" },
                { name: "男科用药" },
                { name: "体检套餐", isHot: true },
                { name: "血糖仪" },
                { name: "保健理疗", isHot: true },
                { name: "针灸拔罐" },
                { name: "成人用品" },
                { name: "男用延时" },
                { name: "女用情趣" },
                { name: "避孕套" },
                { name: "润滑剂" },
                { name: "情趣跳蛋" },
                { name: "飞机杯" },
                { name: "缩阴球" },
                { name: "震动棒" },
                { name: "肾宝片" },
                { name: "阳痿早泄", isHot: true },
                { name: "伟哥", isHot: true },
                { name: "肝炎", isHot: true },
                { name: "皮炎湿疹", isHot: true },
              ],
            },
            {
              title: "医疗器械",
              items: [
                { name: "制氧机", isHot: true },
                { name: "体温计" },
                { name: "轮椅", isHot: true },
                { name: "胎心仪" },
                { name: "理疗仪", isHot: true },
                { name: "助听器" },
                { name: "雾化器" },
                { name: "呼吸机", isHot: true },
                { name: "拔罐器" },
                { name: "口罩" },
                { name: "血压计", isHot: true },
                { name: "创口贴" },
                { name: "护具" },
                { name: "导尿袋" },
                { name: "血糖仪", isHot: true },
                { name: "针灸用品" },
                { name: "护理床" },
                { name: "褥疮垫", isHot: true },
                { name: "家用器械" },
                { name: "按摩器材" },
                { name: "吸痰器" },
                { name: "座便椅", isHot: true },
                { name: "血氧仪" },
                { name: "颈椎治疗仪" },
                { name: "刮痧" },
                { name: "洗鼻器" },
              ],
            },
            {
              title: "隐形眼镜",
              items: [
                { name: "强生美瞳", isHot: true },
                { name: "博士伦", isHot: true },
                { name: "海昌" },
                { name: "海俪恩" },
                { name: "卫康", isHot: true },
                { name: "爱尔康", isHot: true },
                { name: "视康" },
                { name: "实瞳" },
                { name: "日抛" },
                { name: "两周抛" },
                { name: "月抛", isHot: true },
                { name: "季抛" },
                { name: "半年抛" },
                { name: "年抛" },
                { name: "护理液", isHot: true },
                { name: "硬镜护理液" },
                { name: "双氧水" },
                { name: "润眼液" },
              ],
            },
            {
              title: "医疗服务",
              items: [
                { name: "爱康国宾", isHot: true },
                { name: "慈铭体检", isHot: true },
                { name: "瑞慈体检", isHot: true },
                { name: "美年大健康" },
                { name: "和睦家", isHot: true },
                { name: "美中宜和" },
                { name: "孕期检查", isHot: true },
                { name: "月子中心", isHot: true },
                { name: "医疗美容", isHot: true },
                { name: "玻尿酸注射" },
                { name: "瘦脸针" },
                { name: "美丽神器" },
                { name: "美白服务", isHot: true },
                { name: "补水服务", isHot: true },
                { name: "齿科" },
                { name: "心理咨询" },
              ],
            },
          ],
        },
        // 厨具 /收纳 /宠物
        {
          hoverColor: "#dd2727",
          detail: [
            {
              title: "厨房烹饪",
              items: [
                { name: "全球家居厨餐具", isHot: true },
                { name: "锅组套装", isHot: true },
                { name: "炒锅", isHot: true },
                { name: "不粘锅" },
                { name: "平底锅" },
                { name: "高压锅" },
                { name: "奶锅" },
                { name: "汤锅" },
                { name: "炖锅", isHot: true },
                { name: "砂锅" },
                { name: "蒸锅" },
                { name: "烧水壶" },
                { name: "刀具", isHot: true },
                { name: "菜刀" },
                { name: "水果刀" },
                { name: "刀架" },
                { name: "菜板" },
                { name: "厨房置物架", isHot: true },
                { name: "烧烤用具" },
                { name: "烘培模具" },
                { name: "烹饪用具" },
                { name: "密封罐" },
                { name: "米桶" },
                { name: "厨房小工具" },
                { name: "厨房清洗" },
              ],
            },
            {
              title: "餐饮具",
              items: [
                { name: "杯具套装", isHot: true },
                { name: "保温杯" },
                { name: "水杯", isHot: true },
                { name: "保温壶" },
                { name: "玻璃杯", isHot: true },
                { name: "陶瓷杯" },
                { name: "茶杯" },
                { name: "咖啡杯" },
                { name: "马克杯" },
                { name: "红酒杯" },
                { name: "水具套装" },
                { name: "酒具" },
                { name: "咖啡具" },
                { name: "餐具", isHot: true },
                { name: "瓷器餐具套装", isHot: true },
                { name: "碗碟套装" },
                { name: "叉勺筷套装" },
                { name: "碗" },
                { name: "筷子" },
                { name: "茶具套装", isHot: true },
                { name: "保温饭盒", isHot: true },
                { name: "保鲜盒" },
                { name: "一次性用品" },
              ],
            },
            {
              title: "居家礼品",
              items: [
                { name: "全球家居", isHot: true },
                { name: "雨伞", isHot: true },
                { name: "太阳伞", isHot: true },
                { name: "雨衣" },
                { name: "口罩", isHot: true },
                { name: "挂钟" },
                { name: "家用梯" },
                { name: "缝纫机", isHot: true },
                { name: "活性炭" },
                { name: "创意礼品" },
                { name: "婚庆用品" },
                { name: "生日礼物" },
                { name: "相册" },
                { name: "劳保用品" },
                { name: "驱虫", isHot: true },
              ],
            },
            {
              title: "收纳清洁",
              items: [
                { name: "全球家居收纳", isHot: true },
                { name: "全球家居清洁", isHot: true },
                { name: "晾衣架" },
                { name: "收纳箱", isHot: true },
                { name: "收纳柜" },
                { name: "鞋柜" },
                { name: "收纳袋" },
                { name: "收纳盒" },
                { name: "化妆包" },
                { name: "旅行收纳" },
                { name: "衣服防尘" },
                { name: "脏衣篮" },
                { name: "压缩袋" },
                { name: "收纳架" },
                { name: "置物架" },
                { name: "旋转拖把", isHot: true },
                { name: "平板拖把" },
                { name: "胶棉拖把" },
                { name: "垃圾桶" },
                { name: "垃圾袋" },
                { name: "置物架" },
                { name: "浴帘" },
                { name: "梳子" },
              ],
            },
            {
              title: "纸品清洁",
              items: [
                { name: "软包抽纸", isHot: true },
                { name: "卷筒纸", isHot: true },
                { name: "手帕纸" },
                { name: "厨房用纸" },
                { name: "湿厕纸" },
                { name: "湿巾纸" },
                { name: "洗衣液", isHot: true },
                { name: "衣物除菌液" },
                { name: "消毒液", isHot: true },
                { name: "洗洁精", isHot: true },
                { name: "油污净" },
                { name: "洁厕剂" },
                { name: "地板清洁" },
                { name: "管道疏通", isHot: true },
                { name: "家私清洁" },
                { name: "玻璃清洁" },
                { name: "驱蚊驱虫", isHot: true },
                { name: "除湿防潮" },
                { name: "驱蚊驱虫" },
                { name: "除甲醛", isHot: true },
              ],
            },
            {
              title: "宠物用品",
              items: [
                { name: "全球家居宠物", isHot: true },
                { name: "狗粮", isHot: true },
                { name: "猫粮", isHot: true },
                { name: "狗零食" },
                { name: "猫零食" },
                { name: "窝/笼" },
                { name: "宠物服饰" },
                { name: "鱼缸", isHot: true },
                { name: "水族世界", isHot: true },
                { name: "牵引带" },
                { name: "医疗保健" },
                { name: "宠物玩具" },
                { name: "猫砂" },
                { name: "生活日用" },
              ],
            },
          ],
        },
        // 图书音像
        {
          hoverColor: "#3bc7b0",
          detail: [
            {
              title: "儿童读物",
              items: [
                { name: "畅销童书" },
                { name: "绘本", isHot: true },
                { name: "儿童文学", isHot: true },
                { name: "启蒙认知" },
                { name: "益智游戏" },
                { name: "幼儿科普" },
                { name: "童话书", isHot: true },
              ],
            },
            {
              title: "畅销小说",
              items: [
                { name: "都市情感", isHot: true },
                { name: "穿越架空" },
                { name: "畅销小说", isHot: true },
                { name: "外国文学" },
                { name: "科幻小说" },
                { name: "影视同期", isHot: true },
              ],
            },
            {
              title: "文学文艺",
              items: [
                { name: "畅销书", isHot: true },
                { name: "散文随笔" },
                { name: "文学" },
                { name: "传记" },
                { name: "涂色", isHot: true },
                { name: "字帖" },
                { name: "现当代文学" },
                { name: "诺贝尔", isHot: true },
                { name: "色铅笔", isHot: true },
              ],
            },
            {
              title: "社科生活",
              items: [
                { name: "烘焙", isHot: true },
                { name: "旅游", isHot: true },
                { name: "菜谱", isHot: true },
                { name: "美容/美体" },
                { name: "时尚", isHot: true },
                { name: "家居装修" },
                { name: "两性健康", isHot: true },
                { name: "两性", isHot: true },
                { name: "减肥" },
              ],
            },
            {
              title: "育儿百科",
              items: [
                { name: "家庭教育" },
                { name: "幼儿情绪管理", isHot: true },
                { name: "能力培养" },
                { name: "胎教", isHot: true },
                { name: "幼儿心理" },
                { name: "孕产妇保健", isHot: true },
              ],
            },
            {
              title: "学习考试",
              items: [
                { name: "公务员", isHot: true },
                { name: "托福" },
                { name: "职称英语" },
                { name: "建造师考试", isHot: true },
                { name: "注册会计师" },
                { name: "四六级英语", isHot: true },
                { name: "考研" },
              ],
            },
            {
              title: "教材教辅",
              items: [
                { name: "中学教辅" },
                { name: "新课标" },
                { name: "中小学作文" },
                { name: "本科/研究生教材", isHot: true },
                { name: "高职教材" },
                { name: "外语学习", isHot: true },
              ],
            },
            {
              title: "经管励志",
              items: [
                { name: "管理学" },
                { name: "金融与投资" },
                { name: "励志" },
                { name: "投资与理财", isHot: true },
                { name: "金融学" },
                { name: "股市" },
                { name: "女性励志", isHot: true },
                { name: "营销" },
              ],
            },
            {
              title: "期刊杂志",
              items: [
                { name: "订阅", isHot: true },
                { name: "国家地理", isHot: true },
                { name: "时尚杂志" },
                { name: "读者", isHot: true },
                { name: "时尚芭莎", isHot: true },
                { name: "昕薇" },
                { name: "瑞丽" },
                { name: "青年文摘", isHot: true },
              ],
            },
            {
              title: "进口原版",
              items: [
                { name: "进口童书", isHot: true },
                { name: "原版小说", isHot: true },
                { name: "原版设计艺术" },
                { name: "原版童书绘本", isHot: true },
                { name: "港台原版书" },
              ],
            },
            {
              title: "大牌乐器",
              items: [
                { name: "乐器" },
                { name: "钢琴", isHot: true },
                { name: "智能钢琴" },
                { name: "数码钢琴" },
                { name: "电子琴", isHot: true },
                { name: "吉他", isHot: true },
                { name: "尤克里里" },
                { name: "古筝" },
                { name: "萨克斯风" },
                { name: "小提琴" },
                { name: "儿童乐器" },
                { name: "口琴" },
                { name: "电吉他" },
                { name: "民谣吉他" },
              ],
            },
          ],
        },
      ],
    };
  },
  methods: {
    changeCategoryIndex(itemIndex) {
      this.selectDetail = this.categoryDetails[itemIndex];
      this.hoverCategoryIndex = itemIndex;
    },
    removeHover() {
      this.hoverCategoryIndex = -1;
    },
  },
};
</script>

<style lang="stylus" scoped>
#category_list:hover .category_detail {
  visibility: visible;
}

#category_list {
  position: relative;

  .category_detail {
    visibility: hidden;
    position: absolute;
    width: 852px;
    height: 500px;
    left: 200px;
    background-color: #fff;
  }

  .categorys {
    position: absolute;
    background-color: rgba(0, 0, 0, 0.55);
    width: 200px;
    height: 500px;
    z-index: 11;

    .category_list_item {
      height: 31.2px;
      color: #fff;

      a {
        height: 31px;
        line-height: 31px;
        color: #fff;
        font-size: 14px;
        white-space: nowrap;
        overflow: hidden;
      }

      span {
        margin-left: 14px;
        margin-right: 4px;
        height: 31px;
        color: #fff;
        opacity: 0.5;
        display: inline-block;
        line-height: 31px;
        vertical-align: middle;
        font-size: 16px;
      }
    }

    li:hover {
      background: #fff;
    }

    li:hover span {
      opacity: 1;
      color: red;
    }

    li:hover a {
      font-weight: 700;
      color: red;
    }
  }
}
</style>